### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by guycalledseven** [dbalduini/smeago#1]
I cannot get it working.  Whatever I do I get len ouf of range error.

```
smeago -h http://www.google.com -p 80
2017/09/29 13:16:26 Crawling Host: http://www.google.com:80
2017/09/29 13:16:26 Urlset Loc: http://localhost
2017/09/29 13:16:26 Sitemap File: /Users/x/test/sitemap.xml
2017/09/29 13:16:26 Visiting: http://www.google.com:80/
panic: runtime error: makeslice: len out of range

goroutine 4 [running]:
github.com/dbalduini/smeago/src.ReadStringSize(0x2a00050, 0xc42000c2c0, 0xffffffffffffffff, 0x2a00050, 0xc42000c2c0, 0xc42008c260)
	/Users/x/go/src/github.com/dbalduini/smeago/src/request.go:19 +0x6e
github.com/dbalduini/smeago/src.(*Crawler).Crawl(0xc4200f2360, 0x1, 0x129e01c, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/x/go/src/github.com/dbalduini/smeago/src/crawler.go:57 +0x2bf
created by github.com/dbalduini/smeago/src.(*CrawlerSupervisor).CrawlJobs
	/Users/x/go/src/github.com/dbalduini/smeago/src/supervisor.go:74 +0x88
```

my go version is go1.9 darwin/amd64

**Comment by dbalduini** [comment]
@guycalledseven Wow, i didn't know someone would use **smeago** besides me.

I will take a look. Maybe i will ask you more information later.

**Comment by guycalledseven** [comment]
@dbalduini with cool name like that, how could I not use it? 👍 
I would be glad to help.

**Comment by dbalduini** [comment]
Sure, if you find something meanwhile you can send me the PR and i will merge it.

**Comment by dbalduini** [comment]
Done!
